Load('TOPAZ_7421:7449',OutputWorkspace='MultiFiles')
CropWorkspace(InputWorkspace='MultiFiles', OutputWorkspace='MultiFiles_crop', XMin=100)
ConvertToMD(InputWorkspace='MultiFiles_crop', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='Q_sample', OutputWorkspace='md')
MergeMD(InputWorkspaces='md', OutputWorkspace='merge')
FindPeaksMD(InputWorkspace='merge', OutputWorkspace='peaks')
FindUBUsingFFT(PeaksWorkspace='peaks', MinD=5, MaxD=10)
ShowPossibleCells('peaks')
SelectCellOfType(PeaksWorkspace='peaks', CellType='Monoclinic', Centering='C', Apply=True)
SaveIsawUB(InputWorkSpace='peaks',Filename='/SNS/users/rwp/TOPAZ_7421-49.mat')
